import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { PGlite } from "@electric-sql/pglite";
import type { SupabaseClient } from "@supabase/supabase-js";
import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, it, vi } from "vitest";
import { compilerFixture } from "./fixtures/door-v44/compiler-fixture";
import { compileDoorV44Page } from "@/domain/search/door-v44/compiler";
import { doorV44Hash } from "@/domain/search/door-v44/schema-engine";
import { doorPageMetadataSchema } from "@/domain/search/door-v44/page-version";
import { prepareDoorPageVersionInput } from "@/domain/search/door-v44/page-version-input";
import { deriveDoorWriterIdentity } from "@/domain/search/door-v44/writer-identity";
import { DOOR_RELEASE_CHECK_IDS, evaluateDoorRelease, issueDoorEvidenceReceipt, type DoorEvidencePayload, type DoorEvidenceReceipt, type DoorEvidenceSubject, type DoorReleasePolicy } from "@/domain/search/door-v44/release-evidence";
import { withdrawDoorSelectionClosure, type DoorPageSelectedEntry, type DoorPageSelectionGuardCommand, type DoorPageSelectionTarget } from "@/domain/search/door-v44/page-selection";
import { doorPageSelectionStore } from "@/platform/search/door-page-selection-store";
import { doorPageVersionStore } from "@/platform/search/door-page-version-store";
import { doorPageVersionInputStore } from "@/platform/search/door-page-version-input-store";
import { doorPageEvidenceStore } from "@/platform/search/door-page-evidence-store";
import { readDevDb, updateDevDb } from "@/platform/stores/dev-db";

// Explicit injected test authority and live-SHAPED candidate. No receipt here is
// operational QA, human approval, or hosted evidence. Original fixture-mode
// samples remain unselectable and are exercised as a negative case below.
const H="a".repeat(64),now=new Date().toISOString(),stamp=(minutes:number)=>new Date(Date.parse(now)+minutes*60000).toISOString();
const audit={actor:"test-owner",reason:"Synthetic selection mechanics only",at:stamp(-20)};
const dependencies=["capability","disclosure","fixture_corpus","prompt","schema","source","template","theme"].map(kind=>({kind,id:"synthetic-test",version:"1",sha256:H}));
const environment={id:"synthetic-selection-test",manifest_sha256:H,commit:"a".repeat(40),origin:"https://fixture.example"};
const policy:DoorReleasePolicy={version:"test-policy",required_checks:[...DOOR_RELEASE_CHECK_IDS],dependencies,environment,max_evidence_age_seconds:86400,
  producers:[{id:"test-system",version:"1",implementation_sha256:H,actor_kind:"system",trust_scope:"governed_execution",kinds:["artifact_integrity","independent_critic","check_matrix","technical_assessment","release_evaluation","revocation"],check_ids:[...DOOR_RELEASE_CHECK_IDS]},
    {id:"test-human",version:"1",implementation_sha256:H,actor_kind:"human",trust_scope:"human_action",kinds:["content_approval","publish_action","review"],check_ids:[]}],holds:{public_publish:false,door_pages_live:true,trial_noindex:true}};
const fence={revision:1,dependency_revision:1,hold_revision:1,dependencies_sha256:doorV44Hash(dependencies),environment_sha256:doorV44Hash(environment),holds_sha256:doorV44Hash(policy.holds)};
const model={status:"recorded" as const,assignments:[{capability:"generate_page_copy",provider:"test",model_id:"test-writer",catalogue_policy_version:"test-policy",run_id:"synthetic-writer-run",record_sha256:H}]};
let fixture:Awaited<ReturnType<typeof compilerFixture>>;let metadata:ReturnType<typeof doorPageMetadataSchema.parse>;let pg:PGlite;let directory:string;let file:string;
const tenant=()=>fixture.spec.identity.tenant_id;
const guard=():DoorPageSelectionGuardCommand=>({tenant_id:tenant(),operation_id:"guard-1",expected_revision:0,...audit,state:{fence,policy_sha256:doorV44Hash(policy),release_policy:policy,origin:environment.origin,index_policy:"trial_noindex",publish_enabled:true,blocked_page_ids:[],family_routes:[{family_id:fixture.spec.identity.family_id,path:"/appliances",label:"Synthetic family"}]}});
function sqlClient():SupabaseClient {return {rpc:async(name:string,{p_input}: {p_input:unknown})=>{await pg.exec("savepoint rpc_call");try{const data=(await pg.query<{r:unknown}>(`select public.${name}($1::jsonb) r`,[JSON.stringify(p_input)])).rows[0].r;await pg.exec("release savepoint rpc_call");return {data,error:null};}catch(e){await pg.exec("rollback to savepoint rpc_call");return{data:null,error:{message:String(e)}};}},
  from:(table:string)=>({select:(columns:string)=>{const filters:Array<[string,string]>=[];const query={eq:(key:string,value:string)=>{filters.push([key,value]);return query;},then:async(resolve:(v:unknown)=>unknown)=>{try{return resolve({data:(await pg.query(`select ${columns} from public.${table} where ${filters.map(([key],i)=>`${key}=$${i+1}`).join(" and ")}`,filters.map(([,value])=>value))).rows,error:null});}catch(e){return resolve({data:null,error:{message:String(e)}});}}};return query;}})} as unknown as SupabaseClient;}
const provider=(adapter:string)=>adapter==="file"?()=>null:()=>sqlClient();
const store=(adapter:string)=>doorPageSelectionStore(provider(adapter),()=>now,async()=>fence);
async function seed(adapter:string,live=true) {
  const versions=doorPageVersionStore(provider(adapter));const identity=fixture.spec.identity;
  const reservation=await versions.reserveVersion({tenant_id:identity.tenant_id,page_id:identity.page_id,canonical_intent_id:identity.canonical_intent_id,canonical_url:new URL(identity.canonical_path,environment.origin).href,operation_id:"candidate",expected_latest_version:0,...audit});
  const captured={tenant_id:tenant(),page_id:identity.page_id,reservation_id:reservation.reservation_id,spec:fixture.spec,context:fixture.context,model_provenance:model,...audit};
  const record=prepareDoorPageVersionInput(captured,reservation).record;
  // Real capture and registration APIs preserve all hashes/audits; no fabricated
  // metadata is inserted directly. The optional negative uses original fixtures.
  if(!live) {const original=await compilerFixture();captured.spec=original.spec;captured.context=original.context;}
  const saved=await doorPageVersionInputStore(provider(adapter)).captureInput(captured);
  let m=metadata;if(!live){const result=await compileDoorV44Page(captured.spec,captured.context);if(!result.ok)throw new Error(JSON.stringify(result.errors));m=doorPageMetadataSchema.parse({receipt:result.receipt,receipt_sha256:doorV44Hash(result.receipt),provenance_status:"unattested",build_provenance_sha256:null});}
  await versions.registerVersion({tenant_id:tenant(),page_id:identity.page_id,reservation_id:reservation.reservation_id,metadata:m,...audit});
  const subject:DoorEvidenceSubject={tenant_id:tenant(),page_id:identity.page_id,page_version:1,reservation_id:reservation.reservation_id,input_sha256:saved.input_sha256,artifact_hash:m.receipt.artifact_hash,compile_receipt_sha256:m.receipt_sha256};
  const receipt=(kind:DoorEvidenceReceipt["kind"],output:unknown,n:number,changes:Record<string,unknown>={})=>{const human=["content_approval","publish_action","review"].includes(kind);return issueDoorEvidenceReceipt({format:"door-v44-evidence/1.0.0",subject,kind,producer:{id:human?"test-human":"test-system",version:"1",implementation_sha256:H,run_id:"synthetic-run",actor_id:human?audit.actor:"test-system",actor_kind:human?"human":"system",trust_scope:human?"human_action":"governed_execution"},dependencies,environment,started_at:stamp(n),finished_at:stamp(n+1),expires_at:stamp(60),verdict:"PASS",findings:[],attachments:[],output,...changes} as DoorEvidencePayload);};
  const rows=[receipt("artifact_integrity",{artifact_read_verified:true,semantic_verified:true,input_verified:true},-18),receipt("independent_critic",{provider:"test",model_id:"test-critic",generation_id:null,prompt_id:"test-prompt",prompt_version:"1",prompt_sha256:H,policy_sha256:H,projection_sha256:H,writer_assignments_sha256:deriveDoorWriterIdentity(record.model_provenance)!.assignments_sha256,repair_iteration:0,prior_attempt_sha256:null,schema_repaired:false,cost_usd:"0.001",usage:{prompt_tokens:1,completion_tokens:1,total_tokens:2}},-16),receipt("check_matrix",{checks:DOOR_RELEASE_CHECK_IDS.map(check_id=>({check_id,verdict:"PASS",result_sha256:H}))},-14)];
  const evaluate=(phase:"technical"|"publish")=>evaluateDoorRelease({phase,subject,receipts:rows,active_receipt_hashes:rows.map(r=>r.receipt_sha256),writer:deriveDoorWriterIdentity(record.model_provenance),policy,fence,now});
  const technical=evaluate("technical");expect(technical.eligible).toBe(true);const output=({eligible,policy_sha256,evidence_hashes,dependencies_sha256,environment_sha256,fence}:ReturnType<typeof evaluate>)=>({eligible,policy_sha256,evidence_hashes,dependencies_sha256,environment_sha256,fence});
  const assessment=receipt("technical_assessment",output(technical),-12);rows.push(assessment);const approval=receipt("content_approval",{assessment_sha256:assessment.receipt_sha256,decision:"APPROVE"},-10);rows.push(approval);
  const released=evaluate("publish");expect(released.eligible,released.reasons.map(r=>r.code).join(",")).toBe(true);const evaluation=receipt("release_evaluation",{...output(released),assessment_sha256:assessment.receipt_sha256,content_approval_sha256:approval.receipt_sha256},-8);rows.push(evaluation);
  const action=receipt("publish_action",{release_evaluation_sha256:evaluation.receipt_sha256,content_approval_sha256:approval.receipt_sha256,expected_selection_revision:0,operation_id:"publish-1",action:"publish",reason:audit.reason},-6);rows.push(action);
  for(const row of rows)await doorPageEvidenceStore(provider(adapter)).appendReceipt(row);
  const target:DoorPageSelectionTarget={...subject,release_evaluation_sha256:evaluation.receipt_sha256,content_approval_sha256:approval.receipt_sha256,publish_action_sha256:action.receipt_sha256};delete (target as Partial<DoorEvidenceSubject>).tenant_id;
  return {target,rows,receipt};
}
beforeAll(async()=>{
 fixture=await compilerFixture();fixture.context.validation.mode="live";fixture.context.validation.index_policy="trial_noindex";fixture.spec.release.index_policy="trial_noindex";fixture.context.intent_review.receipt_id="synthetic_test_intent_review";
 for(const c of fixture.spec.capabilities)if(c.production_receipt)c.production_receipt=c.production_receipt.replace(/^fixture_/,"synthetic_test_");
 for(const c of fixture.context.validation.capabilities)if(c.production_receipt)c.production_receipt=c.production_receipt.replace(/^fixture_/,"synthetic_test_");
 for(const v of fixture.spec.visuals){v.authored_status="reviewed";v.review_receipt="synthetic_test_visual_review";fixture.context.validation.visual_assets[fixture.context.validation.visual_assets.findIndex(a=>a.asset_id===v.asset_id)]={...structuredClone(v),tenant_id:tenant()};}
 const compiled=await compileDoorV44Page(fixture.spec,fixture.context);if(!compiled.ok)throw new Error(JSON.stringify(compiled.errors));metadata=doorPageMetadataSchema.parse({receipt:compiled.receipt,receipt_sha256:doorV44Hash(compiled.receipt),provenance_status:"unattested",build_provenance_sha256:null});
 pg=new PGlite();await pg.exec("create role anon;create role authenticated;create role service_role bypassrls;grant usage on schema public to anon,authenticated,service_role;");
 for(const name of ["00002_journey_runtime.sql","00003_service_role_grants.sql","00012_page_registry.sql","00013_admin_audit_duration.sql","00028_door_page_versions.sql","00029_door_page_version_inputs.sql","00030_door_page_evidence.sql","00031_door_page_selection.sql"]){try{await pg.exec(readFileSync(`supabase/migrations/${name}`,"utf8"));}catch(e){throw new Error(name+" "+JSON.stringify(e));}}
},20000);
beforeEach(async()=>{directory=mkdtempSync(join(tmpdir(),"door-selection-test-"));file=join(directory,"db.json");vi.stubEnv("PRN_DEV_DB_PATH",file);await pg.exec("begin");});
afterEach(async()=>{await pg.exec("rollback");vi.unstubAllEnvs();rmSync(directory,{recursive:true,force:true});});
afterAll(async()=>{await pg?.close();});

describe.each(["file","sql"])("exact selection %s adapter",adapter=>{
 it("default snapshot holds frozen AC, records managed reservations, and exposes nothing",async()=>{const s=await store(adapter).getServingSnapshot(tenant(),null);expect(s.entries).toEqual([]);expect(s.guard_status).toBe("unconfigured");expect(s.managed).toEqual([{page_id:null,canonical_path:"/problems/ac-blowing-warm-air",kind:"frozen_control"}]);});
 it("commits exact candidate and immutable history only after persisted assessment, approval and action",async()=>{const {target}=await seed(adapter);const s=store(adapter);await s.registerGuard(guard());const c={tenant_id:tenant(),operation_id:"publish-1",expected_revision:0,action:"publish" as const,fence,entries:[target],...audit};const selected=await s.commitSelectionSet(c);expect(selected.entries).toHaveLength(1);expect(selected.entries[0]).toMatchObject({artifact_hash:metadata.receipt.artifact_hash,robots:"noindex,follow",sitemap_eligible:false});expect(await s.commitSelectionSet(c)).toEqual(selected);expect(await s.getSelectionSet(tenant(),1)).toEqual(selected);expect((await s.getServingSnapshot(tenant(),fence)).entries).toEqual(selected.entries);expect((await s.getServingSnapshot(tenant(),null)).entries).toEqual([]);});
 it("requires independent freshness provider and refuses missing or foreign observations",async()=>{await store(adapter).registerGuard(guard());const c={tenant_id:tenant(),operation_id:"publish-1",expected_revision:0,action:"publish" as const,fence,entries:[],...audit};await expect(doorPageSelectionStore(provider(adapter),()=>now).commitSelectionSet(c)).rejects.toMatchObject({code:"SELECTION_HOLD"});await expect(doorPageSelectionStore(provider(adapter),()=>now,async()=>({...fence,hold_revision:99})).commitSelectionSet(c)).rejects.toMatchObject({code:"SELECTION_HOLD"});});
 it("retains fixture-mode candidates as unselectable despite injected PASS-shaped evidence",async()=>{const {target}=await seed(adapter,false);await store(adapter).registerGuard(guard());await expect(store(adapter).commitSelectionSet({tenant_id:tenant(),operation_id:"publish-1",expected_revision:0,action:"publish",fence,entries:[target],...audit})).rejects.toMatchObject({code:"SELECTION_INELIGIBLE"});});
 it("CAS guards and operation retries conflict without partial audit changes",async()=>{const s=store(adapter),c=guard();const g=await s.registerGuard(c);expect(await s.registerGuard(c)).toEqual(g);await expect(s.registerGuard({...c,reason:"Changed reason"})).rejects.toMatchObject({code:"SELECTION_CONFLICT"});await expect(s.registerGuard({...c,operation_id:"competing-guard"})).rejects.toMatchObject({code:"SELECTION_CONFLICT"});expect(await s.getGuard(tenant())).toEqual(g);});
 it("withdraws immediately, preserves history and rejects stale writers",async()=>{const {target}=await seed(adapter);const s=store(adapter);await s.registerGuard(guard());const old=await s.commitSelectionSet({tenant_id:tenant(),operation_id:"publish-1",expected_revision:0,action:"publish",fence,entries:[target],...audit});const c={tenant_id:tenant(),operation_id:"withdraw-1",expected_revision:1,expected_hold_revision:1,page_ids:[target.page_id],...audit};const removed=await s.withdrawSelectionPages(c);expect(removed.entries).toEqual([]);expect(await s.withdrawSelectionPages(c)).toEqual(removed);expect(await s.getSelectionSet(tenant(),1)).toEqual(old);await expect(s.withdrawSelectionPages({...c,operation_id:"stale"})).rejects.toMatchObject({code:"SELECTION_CONFLICT"});expect((await s.getServingSnapshot(tenant(),fence)).entries).toEqual([]);});
 it("new holds atomically append withdrawal and clearing them never republishes",async()=>{const {target}=await seed(adapter);const s=store(adapter);await s.registerGuard(guard());await s.commitSelectionSet({tenant_id:tenant(),operation_id:"publish-1",expected_revision:0,action:"publish",fence,entries:[target],...audit});const held=guard();held.expected_revision=1;held.operation_id="guard-hold";held.state.fence={...fence,revision:2,hold_revision:2};held.state.blocked_page_ids=[target.page_id];await s.registerGuard(held);expect((await s.getSelectionHead(tenant()))?.action).toBe("hold_withdrawal");expect((await s.getSelectionHead(tenant()))?.entries).toEqual([]);const clear=structuredClone(held);clear.expected_revision=2;clear.operation_id="guard-clear";clear.state.fence.revision=3;clear.state.fence.hold_revision=3;clear.state.blocked_page_ids=[];await s.registerGuard(clear);expect((await s.getSelectionHead(tenant()))?.entries).toEqual([]);});
 it("revocation is fresh on every read even when omitted from active evidence",async()=>{const {target,receipt}=await seed(adapter);const s=store(adapter);await s.registerGuard(guard());await s.commitSelectionSet({tenant_id:tenant(),operation_id:"publish-1",expected_revision:0,action:"publish",fence,entries:[target],...audit});await doorPageEvidenceStore(provider(adapter)).appendReceipt(receipt("revocation",{target_receipt_sha256:target.release_evaluation_sha256,reason_code:"synthetic_revocation"},-2));expect((await s.getServingSnapshot(tenant(),fence)).entries).toEqual([]);});
 it("rollback refuses a never-selected version even with a fresh matching human action",async()=>{const {target,receipt}=await seed(adapter);const s=store(adapter);await s.registerGuard(guard());const action=receipt("publish_action",{release_evaluation_sha256:target.release_evaluation_sha256,content_approval_sha256:target.content_approval_sha256,expected_selection_revision:0,operation_id:"rollback-new",action:"rollback",reason:audit.reason},-4);await doorPageEvidenceStore(provider(adapter)).appendReceipt(action);await expect(s.commitSelectionSet({tenant_id:tenant(),operation_id:"rollback-new",expected_revision:0,action:"rollback",fence,entries:[{...target,publish_action_sha256:action.receipt_sha256}],...audit})).rejects.toMatchObject({code:"SELECTION_INELIGIBLE"});expect(await s.getSelectionHead(tenant())).toBeNull();});
 it("rollback restores an exact previously selected artifact after withdrawal with fresh action",async()=>{const {target,receipt}=await seed(adapter);const s=store(adapter);await s.registerGuard(guard());await s.commitSelectionSet({tenant_id:tenant(),operation_id:"publish-1",expected_revision:0,action:"publish",fence,entries:[target],...audit});await s.withdrawSelectionPages({tenant_id:tenant(),operation_id:"withdraw",expected_revision:1,expected_hold_revision:1,page_ids:[target.page_id],...audit});const action=receipt("publish_action",{release_evaluation_sha256:target.release_evaluation_sha256,content_approval_sha256:target.content_approval_sha256,expected_selection_revision:2,operation_id:"rollback-old",action:"rollback",reason:audit.reason},-4);await doorPageEvidenceStore(provider(adapter)).appendReceipt(action);const restored=await s.commitSelectionSet({tenant_id:tenant(),operation_id:"rollback-old",expected_revision:2,action:"rollback",fence,entries:[{...target,publish_action_sha256:action.receipt_sha256}],...audit});expect(restored.revision).toBe(3);expect(restored.entries[0].artifact_hash).toBe(target.artifact_hash);expect((await s.getServingSnapshot(tenant(),fence)).entries).toEqual(restored.entries);});
 it("rejects stale action operation and cross-tenant candidate targets",async()=>{const {target}=await seed(adapter);const s=store(adapter);await s.registerGuard(guard());await expect(s.commitSelectionSet({tenant_id:tenant(),operation_id:"wrong-action",expected_revision:0,action:"publish",fence,entries:[target],...audit})).rejects.toMatchObject({code:"SELECTION_INELIGIBLE"});const foreign=guard();foreign.tenant_id="foreign";await s.registerGuard(foreign);await expect(s.commitSelectionSet({tenant_id:"foreign",operation_id:"publish-1",expected_revision:0,action:"publish",fence,entries:[target],...audit})).rejects.toMatchObject({code:"SELECTION_INELIGIBLE"});});
});
it("withdrawal closure removes inbound chains while retaining unrelated exact rows",()=>{const a={page_id:"a",related_page_ids:["b"]},b={page_id:"b",related_page_ids:["c"]},c={page_id:"c",related_page_ids:[]},d={page_id:"d",related_page_ids:[]};expect(withdrawDoorSelectionClosure([a,b,c,d] as DoorPageSelectedEntry[],["c"]).map(r=>r.page_id)).toEqual(["d"]);});
it("file history detects deletion and altered audit while preserving unrelated collections",async()=>{updateDevDb(db=>{db.published_page_ids.push("legacy-untouched");});const s=store("file");await s.registerGuard(guard());expect(readDevDb().published_page_ids).toEqual(["legacy-untouched"]);const saved=readFileSync(file,"utf8");const corrupted=JSON.parse(saved);corrupted.door_page_selection_guards=[];writeFileSync(file,JSON.stringify(corrupted));await expect(s.getGuard(tenant())).rejects.toMatchObject({code:"SELECTION_CORRUPT"});writeFileSync(file,saved);const changed=JSON.parse(saved);changed.admin_audit[0].detail="{}";writeFileSync(file,JSON.stringify(changed));await expect(s.getGuard(tenant())).rejects.toMatchObject({code:"SELECTION_CORRUPT"});});
it("direct anon/authenticated cannot read or mutate selection; even elevated history updates are immutable",async()=>{await store("sql").registerGuard(guard());for(const role of ["anon","authenticated"]){await pg.exec("savepoint acl");await pg.exec(`set local role ${role}`);await expect(pg.query("select * from door_page_selection_guard")).rejects.toThrow();await pg.exec("rollback to savepoint acl");}await pg.exec("savepoint immutable");await expect(pg.exec("update door_page_selection_guard set operation_id='forged'")).rejects.toThrow();await pg.exec("rollback to savepoint immutable");});
it("SQL audit failure rolls back guard, head and immutable set writes",async()=>{await pg.exec("create function reject_selection_audit() returns trigger language plpgsql as $$ begin raise exception 'synthetic audit failure'; end $$;create trigger reject_selection_audit before insert on admin_audit for each row execute function reject_selection_audit();");await expect(store("sql").registerGuard(guard())).rejects.toMatchObject({code:"SELECTION_UNAVAILABLE"});expect((await pg.query("select * from door_page_selection_guard")).rows).toHaveLength(0);expect((await pg.query("select * from door_page_selection_head")).rows).toHaveLength(0);});
it.each(["foreign","missing-frozen","extra"])("rejects %s configured-client snapshot without file fallback",async(kind)=>{const s=await store("file").getServingSnapshot(tenant(),null);if(kind==="foreign")s.tenant_id="foreign";if(kind==="missing-frozen")s.managed=[];const raw=kind==="extra"?{...s,private_payload:"forbidden"}:s;const client={rpc:async()=>({data:raw,error:null})} as unknown as SupabaseClient;await expect(doorPageSelectionStore(()=>client).getServingSnapshot(tenant(),null)).rejects.toMatchObject({code:"SELECTION_CORRUPT"});});
it("a guard change racing independent freshness prevents commit against old observation",async()=>{const s=store("file");await s.registerGuard(guard());const racing=doorPageSelectionStore(()=>null,()=>now,async()=>{const changed=guard();changed.operation_id="raced";changed.expected_revision=1;changed.state.fence={...fence,revision:2,hold_revision:2};await s.registerGuard(changed);return fence;});await expect(racing.commitSelectionSet({tenant_id:tenant(),operation_id:"publish-1",expected_revision:0,action:"publish",fence,entries:[],...audit})).rejects.toMatchObject({code:"SELECTION_HOLD"});expect(await s.getSelectionHead(tenant())).toBeNull();});
