/** Generated by the offline fixture packager. Byte identity only; never review or execution attestation. */
export const DOOR_FIXTURE_PACKAGE_SHA256 = "c552594c99c7ed6d6dffa9d475de8bcd497ce838cf3bc011fd358df363e8cecc";
