/** Offline packaging only. The server never imports this generator or test factories. */
import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync, statSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { corpusDefinitions, corpusFixture } from "../../tests/fixtures/door-v44/corpus/corpus-fixture";
import { convertF01 } from "../../tests/fixtures/door-v44/corpus/f01/convert";
import { doorV44Hash, stableDoorJson } from "../../src/domain/search/door-v44/schema-engine";

const root = process.cwd(), destination = join(root, "content/door-v44-fixtures/v1");
const pinPath = "src/platform/search/door-page-run-fixture-pin.ts";
const digest = (bytes: string | Buffer) => createHash("sha256").update(bytes).digest("hex");
async function sources() {
  const seen = new Set<string>();
  async function visit(path: string): Promise<void> {
    path = path.replaceAll("\\", "/");
    if (seen.has(path) || path === pinPath) return;
    seen.add(path);
    if (!/\.tsx?$/.test(path)) return;
    const body = await readFile(join(root, path), "utf8");
    for (const match of body.matchAll(/(?:from\s*|import\s*)["']([^"']+)["']/g)) {
      const ref = match[1];
      if (!ref.startsWith(".") && !ref.startsWith("@/")) continue;
      const base = ref.startsWith("@/") ? join(root, "src", ref.slice(2)) : resolve(root, dirname(path), ref);
      const actual = [base, base + ".ts", base + ".tsx", join(base, "index.ts")].find(candidate => existsSync(candidate) && statSync(candidate).isFile());
      if (!actual) throw new Error("Fixture source closure missing");
      await visit(relative(root, actual));
    }
  }
  await visit("src/platform/search/door-page-run-fixtures.ts");
  await visit("src/platform/search/door-page-run-executor.ts");
  seen.add("package.json"); seen.add("package-lock.json");
  return Promise.all([...seen].sort().map(async path => {
    const raw = await readFile(join(root, path)), lf = raw.toString("utf8").replaceAll("\r\n", "\n");
    return { path, raw_sha256: digest(raw), lf_sha256: digest(lf), crlf_sha256: digest(lf.replaceAll("\n", "\r\n")) };
  }));
}
async function main() {
  if (process.argv.length !== 2 || resolve(process.argv[1]) !== resolve(root, "tools/door-v44/package-run-fixtures.ts")) throw new Error("Fixture packaging invocation invalid");
  const conversion = convertF01(root), report = conversion.report;
  const entries: Array<{ fixture_id: string; label: string; data: unknown }> = [{ fixture_id: "F01", label: "AC blowing warm air — blocked source control", data: {
    fixture_id: "F01", status: report.status, candidate_hash: report.candidate_hash, source_pin_hash: report.source_pin_hash, report_sha256: doorV44Hash(report),
    diagnostics: report.blockers.flatMap(row => row.pointers.map(pointer => ({ code: row.code, pointer }))), release_ready: false, compiler_pass: false,
  } }];
  for (const definition of corpusDefinitions) { const { spec, context } = await corpusFixture(definition.id); entries.push({ fixture_id: definition.id, label: definition.query, data: { fixture_id: definition.id, spec, context } }); }
  await mkdir(destination, { recursive: true });
  const files = [];
  for (const entry of entries) {
    const path = entry.fixture_id.toLowerCase() + ".json", bytes = Buffer.from(stableDoorJson(entry.data) + "\n", "utf8");
    await writeFile(join(destination, path), bytes);
    files.push({ fixture_id: entry.fixture_id, label: entry.label, path, sha256: digest(bytes), bytes: bytes.length });
  }
  const closure = await sources();
  const manifest = { format: "door-fixture-package/1.0.0", executor_version: "door-fixture-executor-1.0.0", executor_sha256: doorV44Hash(closure),
    provenance: "synthetic_nonpublic_no_review_or_execution_attestation", fixtures: files, sources: closure };
  const body = stableDoorJson(manifest) + "\n", sha = digest(body);
  await writeFile(join(destination, "manifest.json"), body, "utf8");
  await writeFile(join(root, pinPath), '/** Generated by the offline fixture packager. Byte identity only; never review or execution attestation. */\nexport const DOOR_FIXTURE_PACKAGE_SHA256 = "' + sha + '";\n', "utf8");
  process.stdout.write(JSON.stringify({ package_sha256: sha, executor_sha256: manifest.executor_sha256, files: files.length, execution_sources: closure.length, model_calls: 0, release_ready: false }) + "\n");
}
main().catch(error => { process.stderr.write("FIXTURE_PACKAGING_FAILED: " + String(error) + "\n"); process.exitCode = 1; });
